include:
  - project: 'resengit/gitlab/pipeline-helpers'
    ref: main
    file: '/common.yaml'
  - project: 'resengit/gitlab/pipeline-helpers'
    ref: main
    file: '/jobs/docker.yaml'

build_docker:
  extends: .build_with_kaniko
  variables:
    PH_KANIKO_OPTS: --cache-copy-layers=false
