// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: servers/protobuf/etim/server.proto

package etim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfrastructureModel_Node_NodeType int32

const (
	InfrastructureModel_Node_COMPUTE InfrastructureModel_Node_NodeType = 0 // default value if not set
	InfrastructureModel_Node_NETWORK InfrastructureModel_Node_NodeType = 1
)

// Enum value maps for InfrastructureModel_Node_NodeType.
var (
	InfrastructureModel_Node_NodeType_name = map[int32]string{
		0: "COMPUTE",
		1: "NETWORK",
	}
	InfrastructureModel_Node_NodeType_value = map[string]int32{
		"COMPUTE": 0,
		"NETWORK": 1,
	}
)

func (x InfrastructureModel_Node_NodeType) Enum() *InfrastructureModel_Node_NodeType {
	p := new(InfrastructureModel_Node_NodeType)
	*p = x
	return p
}

func (x InfrastructureModel_Node_NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InfrastructureModel_Node_NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_servers_protobuf_etim_server_proto_enumTypes[0].Descriptor()
}

func (InfrastructureModel_Node_NodeType) Type() protoreflect.EnumType {
	return &file_servers_protobuf_etim_server_proto_enumTypes[0]
}

func (x InfrastructureModel_Node_NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InfrastructureModel_Node_NodeType.Descriptor instead.
func (InfrastructureModel_Node_NodeType) EnumDescriptor() ([]byte, []int) {
	return file_servers_protobuf_etim_server_proto_rawDescGZIP(), []int{2, 0, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_protobuf_etim_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_servers_protobuf_etim_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_servers_protobuf_etim_server_proto_rawDescGZIP(), []int{0}
}

type ComputeResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// compute capacity in milliCPU, matches what Kubernetes uses.
	MilliCPU int32 `protobuf:"varint,1,opt,name=milliCPU,proto3" json:"milliCPU,omitempty"`
	// RAM in Bytes, matches what Kubernetes uses internally.
	MemoryInBytes int64 `protobuf:"varint,2,opt,name=memoryInBytes,proto3" json:"memoryInBytes,omitempty"`
}

func (x *ComputeResources) Reset() {
	*x = ComputeResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_protobuf_etim_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResources) ProtoMessage() {}

func (x *ComputeResources) ProtoReflect() protoreflect.Message {
	mi := &file_servers_protobuf_etim_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResources.ProtoReflect.Descriptor instead.
func (*ComputeResources) Descriptor() ([]byte, []int) {
	return file_servers_protobuf_etim_server_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeResources) GetMilliCPU() int32 {
	if x != nil {
		return x.MilliCPU
	}
	return 0
}

func (x *ComputeResources) GetMemoryInBytes() int64 {
	if x != nil {
		return x.MemoryInBytes
	}
	return 0
}

type InfrastructureModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*InfrastructureModel_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *InfrastructureModel) Reset() {
	*x = InfrastructureModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_protobuf_etim_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfrastructureModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureModel) ProtoMessage() {}

func (x *InfrastructureModel) ProtoReflect() protoreflect.Message {
	mi := &file_servers_protobuf_etim_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureModel.ProtoReflect.Descriptor instead.
func (*InfrastructureModel) Descriptor() ([]byte, []int) {
	return file_servers_protobuf_etim_server_proto_rawDescGZIP(), []int{2}
}

func (x *InfrastructureModel) GetNodes() []*InfrastructureModel_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type InfrastructureModel_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Can be compute node or network node.
	NodeType InfrastructureModel_Node_NodeType `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=server_proto.InfrastructureModel_Node_NodeType" json:"node_type,omitempty"`
	// CPU Architecture
	CpuArchitecture string `protobuf:"bytes,3,opt,name=cpu_architecture,json=cpuArchitecture,proto3" json:"cpu_architecture,omitempty"`
	// These are the total resources in the node.
	// The resource fields are empty for Network nodes.
	Resources *ComputeResources `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	// These are the resources on the node that are available to allocate.
	AvailableResources *ComputeResources `protobuf:"bytes,5,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	// Nodes can be labelled to indicate capabilities, architecture,
	// maybe the security zone.
	Labels []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *InfrastructureModel_Node) Reset() {
	*x = InfrastructureModel_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_protobuf_etim_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfrastructureModel_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureModel_Node) ProtoMessage() {}

func (x *InfrastructureModel_Node) ProtoReflect() protoreflect.Message {
	mi := &file_servers_protobuf_etim_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureModel_Node.ProtoReflect.Descriptor instead.
func (*InfrastructureModel_Node) Descriptor() ([]byte, []int) {
	return file_servers_protobuf_etim_server_proto_rawDescGZIP(), []int{2, 0}
}

func (x *InfrastructureModel_Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfrastructureModel_Node) GetNodeType() InfrastructureModel_Node_NodeType {
	if x != nil {
		return x.NodeType
	}
	return InfrastructureModel_Node_COMPUTE
}

func (x *InfrastructureModel_Node) GetCpuArchitecture() string {
	if x != nil {
		return x.CpuArchitecture
	}
	return ""
}

func (x *InfrastructureModel_Node) GetResources() *ComputeResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *InfrastructureModel_Node) GetAvailableResources() *ComputeResources {
	if x != nil {
		return x.AvailableResources
	}
	return nil
}

func (x *InfrastructureModel_Node) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_servers_protobuf_etim_server_proto protoreflect.FileDescriptor

var file_servers_protobuf_etim_server_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x74, 0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x54, 0x0a, 0x10, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x43, 0x50, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x43, 0x50, 0x55, 0x12, 0x24, 0x0a, 0x0d, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x22, 0xb2, 0x03, 0x0a, 0x13, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0xdc, 0x02, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x4c, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29,
	0x0a, 0x10, 0x63, 0x70, 0x75, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x70, 0x75, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x13, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x52, 0x12, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x22, 0x24, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54,
	0x57, 0x4f, 0x52, 0x4b, 0x10, 0x01, 0x32, 0x58, 0x0a, 0x0a, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x4a, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54,
	0x6f, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66,
	0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x42, 0x18, 0x5a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x74, 0x69, 0x6d, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_servers_protobuf_etim_server_proto_rawDescOnce sync.Once
	file_servers_protobuf_etim_server_proto_rawDescData = file_servers_protobuf_etim_server_proto_rawDesc
)

func file_servers_protobuf_etim_server_proto_rawDescGZIP() []byte {
	file_servers_protobuf_etim_server_proto_rawDescOnce.Do(func() {
		file_servers_protobuf_etim_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_servers_protobuf_etim_server_proto_rawDescData)
	})
	return file_servers_protobuf_etim_server_proto_rawDescData
}

var file_servers_protobuf_etim_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servers_protobuf_etim_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_servers_protobuf_etim_server_proto_goTypes = []interface{}{
	(InfrastructureModel_Node_NodeType)(0), // 0: server_proto.InfrastructureModel.Node.NodeType
	(*Empty)(nil),                          // 1: server_proto.Empty
	(*ComputeResources)(nil),               // 2: server_proto.ComputeResources
	(*InfrastructureModel)(nil),            // 3: server_proto.InfrastructureModel
	(*InfrastructureModel_Node)(nil),       // 4: server_proto.InfrastructureModel.Node
}
var file_servers_protobuf_etim_server_proto_depIdxs = []int32{
	4, // 0: server_proto.InfrastructureModel.nodes:type_name -> server_proto.InfrastructureModel.Node
	0, // 1: server_proto.InfrastructureModel.Node.node_type:type_name -> server_proto.InfrastructureModel.Node.NodeType
	2, // 2: server_proto.InfrastructureModel.Node.resources:type_name -> server_proto.ComputeResources
	2, // 3: server_proto.InfrastructureModel.Node.available_resources:type_name -> server_proto.ComputeResources
	1, // 4: server_proto.Aggregator.ConnectToQuerier:input_type -> server_proto.Empty
	3, // 5: server_proto.Aggregator.ConnectToQuerier:output_type -> server_proto.InfrastructureModel
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_servers_protobuf_etim_server_proto_init() }
func file_servers_protobuf_etim_server_proto_init() {
	if File_servers_protobuf_etim_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servers_protobuf_etim_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_protobuf_etim_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_protobuf_etim_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfrastructureModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_protobuf_etim_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfrastructureModel_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servers_protobuf_etim_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_protobuf_etim_server_proto_goTypes,
		DependencyIndexes: file_servers_protobuf_etim_server_proto_depIdxs,
		EnumInfos:         file_servers_protobuf_etim_server_proto_enumTypes,
		MessageInfos:      file_servers_protobuf_etim_server_proto_msgTypes,
	}.Build()
	File_servers_protobuf_etim_server_proto = out.File
	file_servers_protobuf_etim_server_proto_rawDesc = nil
	file_servers_protobuf_etim_server_proto_goTypes = nil
	file_servers_protobuf_etim_server_proto_depIdxs = nil
}
