name: Pipeline for the Edge Monitoring Aggregator
# CICD only is activated when:
# - there is a push to a PR from any branch to any branch
# - the protected branches are updated
on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'develop'

env:
  # Needed for the target repo in nexus
  # SNS_REGISTRY_COMMON: registry.atosresearch.eu:18467
  # Needed for the dockerfile base image
  TMT_REGISTRY_COMMON: registry.atosresearch.eu:18488
  # Needed for the target repo in nexus
  ETIM_REGISTRY_ICOS: registry.atosresearch.eu:18484
  IMAGE_NAME: icos-server-linux

jobs:
  build_and_push_image:
    name: Build Docker Image
    runs-on: [self-hosted]
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure and use https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Decide the tag of the image
        id: get_tag
        # Only 3 tags in nexus (cicd, shared for all developers with an open PR), main and develop
        # TODO: would be nice to have PR-specific version and delete them after some time or similar
        shell: bash
        run: |
          echo "::set-output name=tag::$(([ ${{ github.ref_name }} == 'main' ] || [ ${{ github.ref_name }} == 'develop' ]) && echo "${{ github.ref_name }}" || echo "cicd")"
      - name: Login to Nexus ETIM
        uses: docker/login-action@v2
        with:
          registry: https://${{ env.ETIM_REGISTRY_ICOS }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PAT }}
      - name: Login to Nexus TMT
        uses: docker/login-action@v2
        with:
          registry: https://${{ env.TMT_REGISTRY_COMMON }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.ETIM_REGISTRY_ICOS }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.tag }}
          file: Dockerfile
          #network: host
          # Used to download ETSN common python libraries
          # TODO: refactor to GH when ready
          # build-args: |
            # USER_NAME=${{ secrets.GL_USER }}
            # USER_PASSWORD=${{ secrets.GL_PAT }}
# Pending to add tests and publish job
